### ISSUE TITLE
Add support for `TimeArray` from TimeSeries.jl

### ISSUE THREAD

**Issue by jayvn** [colintbowers/DependentBootstrap.jl#4]
Hi,
I'd like to add the methods to support `TimeArray` Suggestions?

**Comment by jayvn** [comment]
This would add a dependency on `TimeSeries.jl`, or we can just add dependancy on `Require.jl` and support future types like `Temporal.jl`, with just `Requires.jl`.

**Comment by colintbowers** [comment]
Thanks for taking the time to work on this.

I agree that this package should support both dataframes, as well as some sort of specific time-series object eventually. However, the last time I looked, `TimeArray` was in its infancy, and I couldn't really justify the additional dependencies when it wasn't even certain what would be the standard going forward.

Personally, I think it is still a bit early to decide. Once we get a month or two into v1.0, I would have thought that would be an appropriate time to start adding dependencies. And I'm certainly loathe to add dependencies a few weeks before v0.7. As it stands, when v0.7 stable hits, nothing (fingers crossed) should break in this package. But if we add a dependency on `TimeArray` (or `DataFrames`) you can absolutely guarantee it'll be broken a few weeks from now.

I think we should leave the PR open for now, and look again at merging in a couple of months.

**Comment by jayvn** [comment]
Thanks for considering this.
I'm OK with leaving the PR open, but do not understand fully the need to do so.
My implementation relies on Requires.jl, which does not add the dependency, but loads the TimeSeries specific methods only when TimeSeries package is loaded. 

So the only dependency is on Requires.jl, and I'm not sure if it will cause problems in Julia 0.7.

**Comment by colintbowers** [comment]
Yeah, so it turns out I actually had absolutely no idea what Requires.jl does. I've just learned something new, thank you!

In hindsight, it makes perfect sense. I might just do a little more testing when I get a moment towards the end of the week, just to be sure I properly understand it, but once that is done, I'll merge the PR. Thanks again. This is obviously the most elegant way to handle adding support for data-frames too!

**Comment by jayvn** [comment]
Thanks for understanding. You've made a great package, it's a privilege to work on it. I do hope there are no side effects with this approach, (only one I can think of is the inability for precompilation at the `@require` block but that shouldn't be an issue). If there is anything I've missed, I'm ready to wait for 0.7.

**Comment by colintbowers** [comment]
Thanks for the complement. I actually hadn't looked at the package in about a year or so, but I just had look over it then and am tempted to make a few other changes in the next week or two. 

For example, it seems insane in hindsight that I made most of the types mutable, when all they contain is a small number of concrete fields. Similarly, I can think of reasons it might be useful to be able to dispatch `BootInput` on function type down the track, so I might change the currently abstract `Function` fields to instead be parametric, ie `Tf<:Function`. Given that you've looked at the package fairly recently, I thought I might ask you your opinion on this here?

**Comment by jayvn** [comment]
Oh yeah, that makes sense. Less code and readability improvement, if I read the code correctly.

**Comment by colintbowers** [comment]
Okay, so I've finally finished all the v1.0 changes. The internals are quite a bit cleaner now, although the user probably won't notice much of a difference (the main difference the user will notice is that `numobs` is no longer a keyword argument since this is now always inferred from the dataset, while the keyword argument fblocklengthcombine has been added for getting a single block length estimate when the dataset is multivariate).

It turned out I needed to restructure the use of `@require` quite a bit since the new `Pkg` system needs all `@require` calls to be in the modules `__init__()` function, and calls also need to include package UUIDs. But it is all sorted out now (hopefully), and TimeArray and DataFrame should both work. Note that I've currently disabled the unit-tests (in runtests.jl) for TimeArray, since that package is still throwing up deprecation warnings for me. I'll come back in a few weeks and uncomment the tests. But they are all passing so there shouldn't be any problems.
